# Generated by Django 6.0.5 on 2026-05-11 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('company_id', models.TextField(blank=True, null=True)),
                ('compounded_sales_growth', models.TextField(blank=True, null=True)),
                ('compounded_profit_growth', models.TextField(blank=True, null=True)),
                ('stock_price_cagr', models.TextField(blank=True, null=True)),
                ('roe', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'analysis',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Balancesheet',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('company_id', models.TextField(blank=True, null=True)),
                ('year', models.TextField(blank=True, null=True)),
                ('equity_capital', models.FloatField(blank=True, null=True)),
                ('reserves', models.BigIntegerField(blank=True, null=True)),
                ('borrowings', models.BigIntegerField(blank=True, null=True)),
                ('other_liabilities', models.BigIntegerField(blank=True, null=True)),
                ('total_liabilities', models.BigIntegerField(blank=True, null=True)),
                ('fixed_assets', models.BigIntegerField(blank=True, null=True)),
                ('cwip', models.BigIntegerField(blank=True, null=True)),
                ('investments', models.BigIntegerField(blank=True, null=True)),
                ('other_asset', models.BigIntegerField(blank=True, null=True)),
                ('total_assets', models.BigIntegerField(blank=True, null=True)),
                ('debt_to_equity', models.FloatField(blank=True, null=True)),
                ('equity_ratio', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'balancesheet',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cashflow',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('company_id', models.TextField(blank=True, null=True)),
                ('year', models.TextField(blank=True, null=True)),
                ('operating_activity', models.FloatField(blank=True, null=True)),
                ('investing_activity', models.FloatField(blank=True, null=True)),
                ('financing_activity', models.FloatField(blank=True, null=True)),
                ('net_cash_flow', models.FloatField(blank=True, null=True)),
                ('free_cash_flow', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cashflow',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('company_logo', models.TextField(blank=True, null=True)),
                ('company_name', models.TextField(blank=True, null=True)),
                ('sector', models.TextField(blank=True, null=True)),
                ('chart_link', models.TextField(blank=True, null=True)),
                ('about_company', models.TextField(blank=True, null=True)),
                ('website', models.TextField(blank=True, null=True)),
                ('nse_profile', models.TextField(blank=True, null=True)),
                ('bse_profile', models.TextField(blank=True, null=True)),
                ('face_value', models.FloatField(blank=True, null=True)),
                ('book_value', models.FloatField(blank=True, null=True)),
                ('roce_percentage', models.FloatField(blank=True, null=True)),
                ('roe_percentage', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'companies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('company_id', models.TextField(blank=True, null=True)),
                ('year', models.BigIntegerField(blank=True, null=True)),
                ('annual_report', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'documents',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FactMlScores',
            fields=[
                ('company_id', models.TextField(primary_key=True, serialize=False)),
                ('company_name', models.TextField(blank=True, null=True)),
                ('computed_at', models.DateTimeField(blank=True, null=True)),
                ('overall_score', models.FloatField(blank=True, null=True)),
                ('profitability_score', models.FloatField(blank=True, null=True)),
                ('growth_score', models.FloatField(blank=True, null=True)),
                ('leverage_score', models.FloatField(blank=True, null=True)),
                ('cashflow_score', models.FloatField(blank=True, null=True)),
                ('stability_score', models.FloatField(blank=True, null=True)),
                ('health_label', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fact_ml_scores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profitandloss',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('company_id', models.TextField(blank=True, null=True)),
                ('year', models.TextField(blank=True, null=True)),
                ('sales', models.BigIntegerField(blank=True, null=True)),
                ('expenses', models.BigIntegerField(blank=True, null=True)),
                ('operating_profit', models.FloatField(blank=True, null=True)),
                ('opm_percentage', models.FloatField(blank=True, null=True)),
                ('other_income', models.BigIntegerField(blank=True, null=True)),
                ('interest', models.BigIntegerField(blank=True, null=True)),
                ('depreciation', models.BigIntegerField(blank=True, null=True)),
                ('profit_before_tax', models.BigIntegerField(blank=True, null=True)),
                ('tax_percentage', models.FloatField(blank=True, null=True)),
                ('net_profit', models.BigIntegerField(blank=True, null=True)),
                ('eps', models.FloatField(blank=True, null=True)),
                ('dividend_payout', models.FloatField(blank=True, null=True)),
                ('net_profit_margin', models.FloatField(blank=True, null=True)),
                ('expense_ratio', models.FloatField(blank=True, null=True)),
                ('interest_coverage', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'profitandloss',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prosandcons',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('company_id', models.TextField(blank=True, null=True)),
                ('pros', models.TextField(blank=True, null=True)),
                ('cons', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'prosandcons',
                'managed': False,
            },
        ),
    ]
